[package]

name = "todo-backend"
version = "0.0.1"
authors = ["Kevin Butler <haqkrs@gmail.com>"]

[dependencies]
nickel = "*"
postgres = "*"
lazy_static = "*"
rustc-serialize = "*"
openssl = "*"
r2d2 = "*"
time = "*"
hyper = "*"

[dependencies.nickel_postgres]
git = "https://github.com/nickel-org/nickel-postgres.git"
